<#
.SYNOPSIS
    One-shot installer for the 9router-mibp-refine fork (server only).
.DESCRIPTION
    Clones the refine repo (unless already inside a checkout), generates a
    secure .env, installs dependencies, builds, and starts the server on
    port 20128 in the foreground. Kept ASCII-only on purpose so Windows
    PowerShell 5.1 reads it cleanly regardless of code page.
.PARAMETER RepoUrl
    Git repo to clone when not already inside a checkout.
.PARAMETER TargetDir
    Directory to clone into / run from (relative to the current directory).
.PARAMETER SkipBuild
    Reuse an existing .next build instead of rebuilding.
.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts/install-server.ps1
.EXAMPLE
    irm https://raw.githubusercontent.com/zuher5/9router-mibp-refine/master/scripts/install-server.ps1 | iex
#>
[CmdletBinding()]
param(
    [string]$RepoUrl = "https://github.com/zuher5/9router-mibp-refine.git",
    [string]$TargetDir = "9router",
    [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"

function New-RandomHex {
    param([int]$Bytes = 32)
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $buf = New-Object byte[] $Bytes
    $rng.GetBytes($buf)
    return [System.BitConverter]::ToString($buf).Replace("-", "").ToLower()
}

# ---------- 1. Locate / prepare the repo ----------
$root = Get-Location
$pkgPath = Join-Path $root "package.json"
$isCheckout = (Test-Path $pkgPath) -and ((Get-Content $pkgPath -Raw -ErrorAction SilentlyContinue) -match "9router-app")
if (-not $isCheckout) {
    $target = Join-Path $root $TargetDir
    if (-not (Test-Path $target)) {
        Write-Host "Cloning refine fork into $target ..." -ForegroundColor Cyan
        git clone --depth 1 $RepoUrl $target
    }
    $root = $target
}
Write-Host "Repo: $root" -ForegroundColor Cyan

# ---------- 2. Node.js version check ----------
$nodeVersion = (& node --version 2>$null) -as [string]
if (-not $nodeVersion) {
    Write-Host "Node.js is required (>= 22). Install it from https://nodejs.org and re-run." -ForegroundColor Red
    exit 1
}
$nodeMajor = [int]($nodeVersion.TrimStart("v") -split "\.")[0]
if ($nodeMajor -lt 22) {
    Write-Host "Node.js $nodeVersion detected; >= 22 is required. Upgrade and re-run." -ForegroundColor Red
    exit 1
}
Write-Host "Node.js $nodeVersion OK" -ForegroundColor Green

# ---------- 3. Generate .env (never overwrite an existing one) ----------
$envFile = Join-Path $root ".env"
if (-not (Test-Path $envFile)) {
    $envContent = @"
# Generated by the 9router-mibp-refine installer - keep this file private.
JWT_SECRET=$(New-RandomHex 32)
INITIAL_PASSWORD=$(New-RandomHex 12)
PORT=20128
NODE_ENV=production
API_KEY_SECRET=$(New-RandomHex 32)
MACHINE_ID_SALT=$(New-RandomHex 32)
ENABLE_REQUEST_LOGS=false
OBSERVABILITY_ENABLED=true
AUTH_COOKIE_SECURE=false
REQUIRE_API_KEY=false
BASE_URL=http://localhost:20128
NEXT_PUBLIC_BASE_URL=http://localhost:20128
CLOUD_URL=https://9router.com
NEXT_PUBLIC_CLOUD_URL=https://9router.com
"@
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($envFile, $envContent, $utf8NoBom)
    Write-Host ".env generated with random secrets." -ForegroundColor Green
} else {
    Write-Host ".env already exists - keeping it." -ForegroundColor Yellow
}

# ---------- 4. Install dependencies ----------
if (-not (Test-Path (Join-Path $root "node_modules"))) {
    Write-Host "Installing dependencies (this can take several minutes)..." -ForegroundColor Cyan
    Push-Location $root
    npm install
    Pop-Location
} else {
    Write-Host "node_modules present - skipping npm install." -ForegroundColor Yellow
}

# ---------- 5. Build (unless skipped and already built) ----------
$standalone = Join-Path $root ".next\standalone\custom-server.js"
if ($SkipBuild -or (Test-Path $standalone)) {
    Write-Host "Using existing build." -ForegroundColor Yellow
} else {
    Write-Host "Building production bundle (next build)..." -ForegroundColor Cyan
    Push-Location $root
    npm run build
    Pop-Location
}

# ---------- 6. Load .env into the process environment and start ----------
$envRaw = (Get-Content $envFile -Raw) -replace "^\uFEFF", ""
$envRaw -split "\r?\n" | ForEach-Object {
    if ($_ -match "^\s*([A-Z0-9_]+)\s*=\s*(.*)$") {
        [System.Environment]::SetEnvironmentVariable($Matches[1], $Matches[2], "Process")
    }
}
$initialPassword = [System.Environment]::GetEnvironmentVariable("INITIAL_PASSWORD", "Process")

Write-Host ""
Write-Host "=============================================================" -ForegroundColor Cyan
Write-Host " 9Router refine fork starting - dashboard:" -ForegroundColor Cyan
Write-Host "   http://localhost:20128/dashboard" -ForegroundColor Green
Write-Host "   Initial password: $initialPassword" -ForegroundColor Green
Write-Host " (change it from the dashboard after first login)" -ForegroundColor DarkGray
Write-Host " Press Ctrl+C to stop the server." -ForegroundColor DarkGray
Write-Host "=============================================================" -ForegroundColor Cyan
Write-Host ""

Push-Location $root
node .next/standalone/custom-server.js