#!/usr/bin/env bash
# One-shot installer for the 9router-mibp-refine fork (server only).
# Clones the repo (unless already inside a checkout), generates a secure .env,
# installs dependencies, builds, and starts the server on port 20128.
# Usage:
#   bash <(curl -fsSL https://raw.githubusercontent.com/zuher5/9router-mibp-refine/master/scripts/install-server.sh)
#   # or after cloning:
#   ./scripts/install-server.sh
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/zuher5/9router-mibp-refine.git}"
TARGET_DIR="${TARGET_DIR:-9router}"
SKIP_BUILD="${SKIP_BUILD:-0}"

info()  { printf '\033[36m%s\033[0m\n' "$*"; }
ok()    { printf '\033[32m%s\033[0m\n' "$*"; }
warn()  { printf '\033[33m%s\033[0m\n' "$*"; }
err()   { printf '\033[31m%s\033[0m\n' "$*" >&2; exit 1; }

rand_hex() {
  local n="${1:-32}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$n"
  else
    head -c "$n" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

# ── 1. Locate / prepare the repo ─────────────────────────────────────────────
ROOT="$PWD"
if [ -f "$ROOT/package.json" ] && grep -q '9router-app' "$ROOT/package.json" 2>/dev/null; then
  : # already inside a checkout
else
  TARGET="$ROOT/$TARGET_DIR"
  if [ ! -d "$TARGET" ]; then
    info "Cloning refine fork into $TARGET ..."
    git clone --depth 1 "$REPO_URL" "$TARGET"
  fi
  ROOT="$TARGET"
fi
info "Repo: $ROOT"

# ── 2. Node.js version check ─────────────────────────────────────────────────
if ! command -v node >/dev/null 2>&1; then
  err "Node.js is required (>= 22). Install it from https://nodejs.org and re-run."
fi
NODE_MAJOR="$(node --version | sed 's/^v//' | cut -d. -f1)"
if [ "$NODE_MAJOR" -lt 22 ]; then
  err "Node.js $(node --version) detected; >= 22 is required. Upgrade and re-run."
fi
ok "Node.js $(node --version)"

# ── 3. Generate .env (never overwrite an existing one) ───────────────────────
ENV_FILE="$ROOT/.env"
if [ ! -f "$ENV_FILE" ]; then
  cat > "$ENV_FILE" <<EOF
# Generated by the 9router-mibp-refine installer — keep this file private.
JWT_SECRET=$(rand_hex 32)
INITIAL_PASSWORD=$(rand_hex 12)
PORT=20128
NODE_ENV=production
API_KEY_SECRET=$(rand_hex 32)
MACHINE_ID_SALT=$(rand_hex 32)
ENABLE_REQUEST_LOGS=false
OBSERVABILITY_ENABLED=true
AUTH_COOKIE_SECURE=false
REQUIRE_API_KEY=false
BASE_URL=http://localhost:20128
NEXT_PUBLIC_BASE_URL=http://localhost:20128
CLOUD_URL=https://9router.com
NEXT_PUBLIC_CLOUD_URL=https://9router.com
EOF
  ok ".env generated with random secrets."
else
  warn ".env already exists — keeping it."
fi

# ── 4. Install dependencies ──────────────────────────────────────────────────
if [ ! -d "$ROOT/node_modules" ]; then
  info "Installing dependencies (this can take several minutes)..."
  ( cd "$ROOT" && npm install )
else
  warn "node_modules present — skipping npm install."
fi

# ── 5. Build (unless skipped and already built) ──────────────────────────────
if [ "$SKIP_BUILD" = "1" ] || [ -f "$ROOT/.next/standalone/custom-server.js" ]; then
  warn "Using existing build."
else
  info "Building production bundle (next build)..."
  ( cd "$ROOT" && npm run build )
fi

# ── 6. Load .env into the environment and start ──────────────────────────────
set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

echo
printf '\033[36m============================================================\033[0m\n'
printf '\033[36m 9Router refine fork starting — dashboard:\033[0m\n'
printf '\033[32m   http://localhost:20128/dashboard\033[0m\n'
printf '\033[32m   Initial password: %s\033[0m\n' "$INITIAL_PASSWORD"
printf '\033[90m (change it from the dashboard after first login)\033[0m\n'
printf '\033[90m Press Ctrl+C to stop the server.\033[0m\n'
printf '\033[36m============================================================\033[0m\n'
echo

cd "$ROOT"
exec node .next/standalone/custom-server.js